# Generated by Django 4.1.5 on 2023-06-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandepermission',
            name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='demandepermission',
            name='envoyeur',
        ),
    ]
