# Generated by Django 4.1.5 on 2023-06-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0002_remove_demandepermission_date_envoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='validee',
            field=models.BooleanField(default=False),
        ),
    ]
