# Generated by Django 4.2.2 on 2023-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0006_remove_demandepermission_validee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='statut',
            field=models.CharField(choices=[('attente_chef', 'En attente de validation par le chef de service'), ('attente_directeur', 'En attente de validation par le directeur général'), ('validee', 'Demande validée')], default='attente_chef', max_length=100),
        ),
    ]
