# Generated by Django 4.2.2 on 2023-06-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0007_alter_demandepermission_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='service',
            field=models.CharField(choices=[('com', 'Commerciale'), ('cli', 'Clientèle'), ('dg', 'Direction'), ('ad', 'Administration')], default='com', max_length=255),
        ),
    ]
