# Generated by Django 4.2.2 on 2023-06-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0009_alter_demandepermission_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='statut',
            field=models.CharField(choices=[('attente_CS', 'En av par le CS'), ('attente_DP', 'En av par le DP'), ('attente_SP', 'En av par le SP'), ('attente_DG', 'En av par le DG'), ('validee', 'Demande validée')], default='attente_chef', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('dg', 'Directeur Général'), ('dp', 'Directeur de Département'), ('sp', 'Service Personnel'), ('ad', 'Administrateur'), ('cs', 'Chef Service'), ('em', 'Employé')], max_length=255),
        ),
    ]
