# Generated by Django 4.2.2 on 2023-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0010_alter_demandepermission_statut_alter_personnel_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.CharField(choices=[('com', 'Commerciale'), ('cli', 'Clientèle'), ('dir', 'Direction'), ('ad', 'Administration')], max_length=255),
        ),
    ]
