# Generated by Django 4.2.2 on 2023-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0011_alter_personnel_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='raison_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='service',
            field=models.CharField(choices=[('com', 'Commerciale'), ('cli', 'Clientèle'), ('dir', 'Direction'), ('ad', 'Administration')], max_length=255),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='statut',
            field=models.CharField(choices=[('attente_CS', 'En av par le CS'), ('attente_DP', 'En av par le DP'), ('attente_SP', 'En av par le SP'), ('attente_DG', 'En av par le DG'), ('validee', 'Demande validée'), ('rejetee', 'Demande rejetée')], default='attente_CS', max_length=100),
        ),
    ]
