# Generated by Django 4.2.2 on 2023-06-29 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0012_demandepermission_raison_rejet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='date_emission',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
