# Generated by Django 4.2.2 on 2023-06-29 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0013_demandepermission_date_emission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='date_emission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='statut',
            field=models.CharField(choices=[('attente_CS', 'En attente par le CS'), ('attente_DP', 'En attente par le DP'), ('attente_SP', 'En attente par le SP'), ('attente_DG', 'En attente par le DG'), ('validee', 'Demande validée'), ('rejetee', 'Demande rejetée')], default='attente_CS', max_length=100),
        ),
    ]
