# Generated by Django 4.2.2 on 2023-06-29 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0014_alter_demandepermission_date_emission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='initiateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_initiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
