# Generated by Django 4.2.2 on 2023-06-30 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0015_demandepermission_initiateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='date_heure_retour',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demandepermission',
            name='date_heure_sortie',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demandepermission',
            name='lieu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='demandepermission',
            name='motif',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='demandepermission',
            name='poste',
            field=models.CharField(choices=[('dg', 'Directeur Général'), ('dp', 'Directeur de Département'), ('sp', 'Service Personnel'), ('ad', 'Administrateur'), ('cs', 'Chef Service'), ('em', 'Employé')], default='em', max_length=100),
        ),
    ]
