# Generated by Django 4.2.2 on 2023-06-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0016_demandepermission_date_heure_retour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandepermission',
            name='DateSortie',
        ),
    ]
