# Generated by Django 4.2.2 on 2023-07-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0019_alter_demandepermission_statut_alter_personnel_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('em', 'Employé'), ('cs', 'Chef Service'), ('ad', 'Administrateur'), ('sp', 'Service Personnel'), ('dg', 'Directeur Général'), ('dp', 'Directeur de Département')], max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.CharField(choices=[('com', 'Commerciale'), ('cli', 'Clientèle'), ('dir', 'Direction'), ('ad', 'Administration')], max_length=255),
        ),
    ]
