# Generated by Django 4.1.5 on 2023-07-13 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0021_demandepermission_validateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='rejeteurs_pour_correction',
            field=models.ManyToManyField(related_name='rejeteurs_pour_correction_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandepermission',
            name='rejeteurs_strict',
            field=models.ManyToManyField(related_name='rejeteurs_strict_demandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
