# Generated by Django 4.1.5 on 2023-07-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0023_alter_demandepermission_date_heure_retour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='lieu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='motif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='poste',
            field=models.CharField(choices=[('dg', 'Directeur Général'), ('dp', 'Directeur de Département'), ('sp', 'Service Personnel'), ('ad', 'Administrateur'), ('cs', 'Chef Service'), ('em', 'Employé')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='statut',
            field=models.CharField(choices=[('attente_CS', 'En attente par le CS'), ('attente_DP', 'En attente par le DP'), ('attente_SP', 'En attente par le SP'), ('attente_DG', 'En attente par le DG'), ('validee', 'Demande validée'), ('rejetee', 'Demande rejetée'), ('a_corriger', 'Demande à corriger')], max_length=100),
        ),
    ]
