# Generated by Django 4.1.5 on 2023-07-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0024_alter_demandepermission_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='raison_rejet',
            field=models.TextField(default=''),
        ),
    ]
