# Generated by Django 4.1.5 on 2023-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0025_alter_demandepermission_raison_rejet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='raison_rejet',
            field=models.TextField(default='rien'),
        ),
    ]
