# Generated by Django 4.1.5 on 2023-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0026_alter_demandepermission_raison_rejet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='raison_rejet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
