# Generated by Django 4.1.5 on 2023-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0028_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepermission',
            name='direction',
            field=models.CharField(choices=[('DirectionTechnique', 'Direction Technique'), ('DirectionCommercialeMarketingCommunication', 'Direction Commerciale, Marketing et Communication'), ('DirectionAdministrativeRessourcesHumaines', 'Direction Administrative et des Ressources Humaines'), ('Direction', 'Direction'), ('Administration', 'Administration')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='direction',
            field=models.CharField(choices=[('DirectionTechnique', 'Direction Technique'), ('DirectionCommercialeMarketingCommunication', 'Direction Commerciale, Marketing et Communication'), ('DirectionAdministrativeRessourcesHumaines', 'Direction Administrative et des Ressources Humaines'), ('Direction', 'Direction'), ('Administration', 'Administration')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='poste',
            field=models.CharField(choices=[('Stagiaire', 'Stagiaire'), ('Employe', 'Employé'), ('ChefService', 'Chef Service'), ('Administrateur', 'Administrateur'), ('ServicePersonnel', 'Service Personnel'), ('DirecteurGeneral', 'Directeur Général'), ('DirecteurDepartement', 'Directeur de Département')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='service',
            field=models.CharField(choices=[('ServiceReseauxClients', 'Service Reseaux et Clients'), ('ServiceSupportAlvanet', 'Service Support ALAVANET'), ('ServiceLogicielFormation', 'Service Logiciel et Formation'), ('ServiceCommercial', 'Service Commercial'), ('ServiceAdministratifRessourcesHumaines', 'Service Administratif et des Ressources Humaines'), ('EquipeLogistiqueCommerciale', 'Equipe Logistique et Commerciale'), ('Direction', 'Direction'), ('Administration', 'Administration')], max_length=255),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='statut',
            field=models.CharField(choices=[('attente_CS', 'En attente du Chef Service'), ('attente_DS', 'En attente du Directeur Service'), ('attente_SP', 'En attente du Service Personnel'), ('attente_DG', 'En attente du Directeur Général'), ('validee', 'Demande validée'), ('rejetee', 'Demande rejetée'), ('a_corriger', 'Demande à corriger')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('Stagiaire', 'Stagiaire'), ('Employe', 'Employé'), ('ChefService', 'Chef Service'), ('Administrateur', 'Administrateur'), ('ServicePersonnel', 'Service Personnel'), ('DirecteurGeneral', 'Directeur Général'), ('DirecteurDepartement', 'Directeur de Département')], max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.CharField(choices=[('ServiceReseauxClients', 'Service Reseaux et Clients'), ('ServiceSupportAlvanet', 'Service Support ALAVANET'), ('ServiceLogicielFormation', 'Service Logiciel et Formation'), ('ServiceCommercial', 'Service Commercial'), ('ServiceAdministratifRessourcesHumaines', 'Service Administratif et des Ressources Humaines'), ('EquipeLogistiqueCommerciale', 'Equipe Logistique et Commerciale'), ('Direction', 'Direction'), ('Administration', 'Administration')], max_length=255),
        ),
    ]
