# Generated by Django 4.1.5 on 2023-07-18 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0031_alter_demandepermission_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='rejeteurs_pour_correction',
            field=models.ManyToManyField(blank=True, null=True, related_name='demandes_rejetees_pour_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='rejeteurs_strict',
            field=models.ManyToManyField(blank=True, null=True, related_name='demandes_strictements_rejetees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='validateurs',
            field=models.ManyToManyField(blank=True, null=True, related_name='demandes_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_vérifiees', to=settings.AUTH_USER_MODEL),
        ),
    ]
