# Generated by Django 4.1.5 on 2023-07-20 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationidsdemande', '0033_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepermission',
            name='rejeteurs_pour_correction',
            field=models.ManyToManyField(blank=True, related_name='demandes_rejetees_pour_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='rejeteurs_strict',
            field=models.ManyToManyField(blank=True, related_name='demandes_strictements_rejetees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepermission',
            name='validateurs',
            field=models.ManyToManyField(blank=True, related_name='demandes_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
